language: python
python:
- '3.8'
install:
- pip install sphinx
- pip install sphinx_rtd_theme
script:
- make -C docs/ html
- touch docs/build/html/.nojekyll
deploy:
- provider: pages:git
  verbose: true
  token: $GITHUB_TOKEN
  egde: true
  local_dir: ./docs/build/html/
  keep_history: true